
on:
  push:
    branches:
      - main

name: 'Deploy to Server'

jobs:

  build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
            
        - name: Docker Setup Buildx
          uses: docker/setup-buildx-action@v3.0.0
    
        - name: Docker Login
          uses: docker/login-action@v3.0.0
          with:
            username: lmcconnell1665
            password: ${{ secrets.docker_pat }}
    
        - name: Build and push Docker images
          uses: docker/build-push-action@v5.0.0
          with:
            # Path to the Dockerfile
            file: ./Dockerfile
            labels: 'mcapi-build'
            platforms: linux/arm64, linux/amd64
            push: true
            secrets: |
              prod=test
            tags: lmcconnell1665/mc-api:latest
              
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set environment variable
        env:
          prod: ${{ secrets.db_server }}
        run: |
          echo "db server is: ${prod}"

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d
