on:
  pull_request:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10

            - name: Activate virtual env
              run: |
                   make setup
                   source ~/.mcapi/bin/activate

            - name: Install dependencies
              run: make install

            - name: Lint with pylint
              run: pylint --disable=R,C mcapi

            - name: Test with pytest
              run: make test

    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
  
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: lmcconnell1665
          password: ${{ secrets.docker_pat }}
  
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          # Path to the Dockerfile
          file: ./Dockerfile
          labels: 'mcapi-build'
          platforms: linux/arm64, linux/amd64
          push: true
          secrets: |
            prod=test
          tags: lmcconnell1665/mc-api:beta
            
